name: release
on: push
jobs:
  build:
    permissions:
      contents: read
      checks: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: temurin
      - run: make build
      - run: ./test.sh
